const products = [
  {
    _id: "1",
    name: "PlayStation 5 (PS5) DualSense langaton ohjain (Midnight Black)",
    image: "/images/controller.jpg",
    description:
      "Discover a deeper, highly immersive gaming experience1 that brings the action to life in the palms of your hands. The DualSense™ wireless controller offers immersive haptic feedback2, dynamic adaptive triggers2 and a built-in microphone, all integrated into an iconic comfortable design.",
    brand: "Sony",
    category: "Electronics",
    price: 69.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 2106,
  },
  {
    _id: "2",
    name: "Cyberpunk 2077 Standard Edition - PlayStation 4, PlayStation 5",
    image: "/images/cyberpunk.jpg",
    description:
      "Cyberpunk 2077 is an open-world, action-adventure story set in Night City, a megalopolis obsessed with power, glamor, and body modification. You play as V, a mercenary outlaw going after a one-of-a-kind implant that is the key to immortality. You can customize your character's cyberware, skill set, and playstyle, and explore a vast city where the choices you make shape the story and world around you.",
    brand: "WB Games",
    category: "Games",
    price: 29.99,
    countInStock: 7,
    rating: 3.2,
    numReviews: 4045,
  },
  {
    _id: "3",
    name: "God of War - PlayStation Hits Standard Edition - PlayStation 4",
    image: "/images/godofwar.jpg",
    description:
      "It is a new beginning for Kratos. Living as a man, outside the shadow of the gods, he seeks solitude in the unfamiliar lands of Norse mythology. With new purpose and his son Atreus at his side, Kratos must fight for survival as powerful forces threaten to disrupt the new life he has created...",
    brand: "Sony",
    category: "Games",
    price: 19.99,
    countInStock: 5,
    rating: 4.9,
    numReviews: 9502,
  },
  {
    _id: "4",
    name: "HyperX - Cloud II Pro Wired Gaming Headset - Red",
    image: "/images/headphone.jpg",
    description:
      "Plan out strategies with your allies using this HyperX Cloud II gaming headset, which features 53 mm drivers and a condenser microphone for clear communication. The audio control box includes a built-in DSP sound card.",
    brand: "HyperX",
    category: "Electronics",
    price: 399.99,
    countInStock: 11,
    rating: 4.6,
    numReviews: 3792,
  },
  {
    _id: "5",
    name: "Asus ROG Strix G513QR 15,6'",
    image: "/images/laptop.jpg",
    description:
      "Take on competitors with this ASUS ROG gaming laptop. The NVIDIA GeForce RTX 3060 graphics card uses tensor cores to provide a clear view of the race track or battlefield, while the AMD Ryzen 9 5900HX processor handles modern titles. Featuring 16GB of RAM, this 15.6-inch ASUS ROG gaming laptop allows seamless multitasking across your games and streaming applications, and the 512GB SSD stores your files.",
    brand: "ASUS",
    category: "Electronics",
    price: 1499.99,
    countInStock: 7,
    rating: 3.7,
    numReviews: 3,
  },
  {
    _id: "6",
    name: "ASUS - TUF 27”",
    image: "/images/monitor.jpg",
    description:
      "Enjoy a smooth gaming experience with this 27-inch ASUS Full HD monitor. The Shadow Boost feature increases clarity in dark scenes, and the ultrafast response times minimize blurring and streaking for seamless gameplay. This ASUS Full HD monitor has an ergonomic design that allows tilting, swiveling and pivoting as needed.",
    brand: "ASUS",
    category: "Electronics",
    price: 349.99,
    countInStock: 0,
    rating: 4.9,
    numReviews: 36,
  },
  {
    _id: "7",
    name: "ASUS - ROG Gaming Desktop",
    image: "/images/pc.jpg",
    description:
      "Annihilate your competition with this ASUS ROG gaming desktop. The Intel Core i7 processor and 16GB of RAM deliver rapid performance during fast-paced action, while the 2TB HDD and a 512GB SSD provide plenty of storage for large files and downloads. This Bluetooth-enabled ASUS ROG gaming computer features an NVIDIA GeForce RTX 3080 graphics card for tear-free rendering of 4K games",
    brand: "ASUS",
    category: "Electronics",
    price: 2099.99,
    countInStock: 12,
    rating: 3.6,
    numReviews: 292,
  },
  {
    _id: "8",
    name: "Sony - PlayStation 5 Console",
    image: "/images/PS5.jpg",
    description:
      "Explore uncharted virtual territories and slay dragons with this sleek Sony PlayStation 5 gaming console. The 825GB SSD allows ultra-fast load times, while 3-D audio output produces crisp acoustics. This Sony PlayStation 5 gaming console supports haptic feedback for effortless communication in multiplayer setups, and adaptive triggers allow immersive gameplay.",
    brand: "Sony",
    category: "Electronics",
    price: 499.99,
    countInStock: 0,
    rating: 4.9,
    numReviews: 19972,
  },
  {
    _id: "9",
    name: "PNY GeForce RTX™ 3080 Ti 12GB",
    image: "/images/rtx3080ti.jpg",
    description:
      "The GeForce RTX™ 3080 Ti delivers the ultra performance that gamers crave, powered by the NVIDIA Ampere architecture. It’s built with enhanced RT Cores and Tensor Cores, new streaming multiprocessors, and superfast G6X memory.",
    brand: "XLRB",
    category: "Electronics",
    price: 1979,
    countInStock: 2,
    rating: 0,
    numReviews: 0,
  },
  {
    _id: "10",
    name: "Marvel's Spider-Man: Miles Morales",
    image: "/images/spiderman.jpg",
    description:
      "In the latest adventure in the Marvel's Spider-Man universe, teenager Miles Morales is adjusting to his new home while following in the footsteps of his mentor, Peter Parker, as a new Spider-Man. But when a fierce power struggle threatens to destroy his new home, the aspiring hero realizes that with great power, there must also come great responsibility. To save all of Marvel's New York, Miles must take up the mantle of Spider-Man and own it.",
    brand: "Sony",
    category: "Games",
    price: 69.99,
    countInStock: 12,
    rating: 4.8,
    numReviews: 1892,
  },
];

export default products;
